{% set version = "2024.5.0" %}
{% set name = "fsspec" %}
{% set sha256 = "1d021b0b0f933e3b3029ed808eb400c08ba101ca2de4b3483fbc9ca23fcee94a" %}

package:
  name: fsspec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - jinja2
    - hatch
    - hatch-vcs
  run:
    - python >=3.8

test:
  requires:
    - pip
  imports:
    - fsspec
  commands:
    - pip check

about:
  home: https://github.com/intake/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/intake/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io
  doc_source_url: https://github.com/intake/filesystem_spec/tree/master/docs
  description: >
    To produce a template or specification for a file-system interface, that specific implementations should follow, so that applications making use of them can rely on a common behaviour and not have to worry about the specific internal implementation decisions with any given backend. Many such implementations are included
    in this package, or in sister projects such as s3fs and gcsfs.

    In addition, if this is well-designed, then additional functionality, such as a key-value store or FUSE mounting of the file-system implementation may be available for all implementations "for free".

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
